/*
 * Autor: Patrick Covre Rodrigues
 * Requerente: João 
 * Data: 12/03/2024
 * Motivo:Dashboard Pedidos de Compras Pendentes
 */
SELECT X.* FROM (
	SELECT 
	CAB.NUNOTA,
	PRO.CODPROD AS Código_Produto,
	PRO.DESCRPROD AS Descrição_Produto,
	PRO.USOPROD AS Usado_Como,
	EST.ESTOQUE,
	EST.ATIVO,
	ITE.VLRUNIT AS VALOR_UNITARIO,
	ITE.VLRTOT AS VALOR_TOTAL,
	ITE.PENDENTE,
	(SELECT SUM(QTDNEG) FROM TGFITE I LEFT JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA WHERE I.CODPROD = PRO.CODPROD AND C.DTENTSAI BETWEEN TO_DATE('01/01/24', 'dd/mm/yy') /*:PERIODO.INI*/ AND /*AND TO_DATE ('0101/2024' ',' 'DD/MM/YY')*/SYSDATE/*:PERIODO.FIN*/) AS QTD_CONSUMO_3MESES,
	SUM(ITE.QTDNEG - ITE.QTDENTREGUE) AS QTDPENDENTE,
	SUM()
	AVG(ITE.QTDNEG) AS QUANTIDADE
	FROM TGFPRO PRO
	LEFT JOIN TGFITE ITE ON ITE.CODPROD = PRO.CODPROD 
	LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
	LEFT JOIN TGFEST EST ON EST.CODPROD = ITE.CODPROD
	WHERE 
	ITE.PENDENTE = 'S' 
	AND PRO.USOPROD = 'M'
	AND EST.ATIVO = 'S'
	GROUP BY
	CAB.NUNOTA,
	PRO.CODPROD,
	PRO.DESCRPROD,
	PRO.USOPROD,
	EST.ESTOQUE,
	EST.ATIVO,
	ITE.VLRUNIT,
	ITE.PENDENTE,
	ITE.VLRTOT
) x
WHERE X.QUANTIDADE > 0